actualización de funciones
grzlz/todo-back pull request #1
Opened 2024-11-07 01:57 UTC by FROY33

2024-11-12 01:11 UTC, grzlz requested changes
registrarUsuario debería guardar encriptar la contraseña y guardarla. Actualmente guarda bien en la tabla, pero no encripta.

2024-11-12 01:23 UTC, FROY33 commented
La encriptación la hace desde el servidor intermedio, desde el +server.js en el front. Pensé que así es más seguro. Quieres que cambie la encriptación a aquí? O que ponga doble?

2024-11-12 01:32 UTC, grzlz commented
Okey, ya vi qué pasó. El otro cacho del código está en el repo del front. Deja veo entonces. Muchas gracias Froy.

2024-11-12 01:34 UTC, FROY33 commented
Quedo atento a cualquier cosa.

2024-11-18 20:40 UTC, grzlz commented
Comienzo a revisar la función de agregarUsuario, ahora debería encriptar la contraseña usando bcrypt.

2024-11-18 21:06 UTC, merged